### ISSUE TITLE
bumpMajor task is always skipped

### ISSUE THREAD

**Issue by alinbutura** [vivin/gradle-semantic-build-versioning#19]
Hi,

We are trying to use the plugin but face issues to have the bumpMajor task increase the version.
We have a git tag which is correctly picked up by printVersion task but nevertheless bumpMajor is always skipped because there are no actions. Can you help? (we ran out of ideas).

Thanks a lot,
Alin

**Comment by vivin** [comment]
Which version are you using? 2.0.1? There was a bug in 2.0.0 that was fixed. Also, what do you get when you do `gradle bumpMajor printVersion`?

**Comment by vivin** [comment]
Also, is there currently already a version tag on `HEAD`?

**Comment by alinbutura** [comment]
As I said we do have the tag "0.0.1" which is printed correctly by printVersion but nevertheless bumpVersion outputs a message saying it was skipped because there are no actions defined.

**Comment by vivin** [comment]
If `HEAD` is already pointing to `0.0.1`, then bumping will not work (should probably output a warning to that effect). This is because the current state of the codebase is version `0.0.1`. If bumping was allowed in this situation, it would be possible to push out a new version with no changes at all (typically not what you want). If you make another commit, or make changes, bumping should work.

**Comment by Vampire** [comment]
@alinbutura the bump tasks are only marker tasks. They do not have any task actions, so they will always be shown as `SKIPPED`. This doesn't mean they did not have any effect. The have effect by sheer presence.

**Comment by vivin** [comment]
@alinbutura Version 2.0.2 checks to see if `HEAD` is already at a tag when bumping and will error out if it is. Can you try it with that version and let me know if that is the case?
