### ISSUE TITLE
project.version is no longer a String when this plugin is active 

### ISSUE THREAD

**Issue by waynr** [vivin/gradle-semantic-build-versioning#4]
Even if I'm not using one of this plugin's tasks, when it is active `project.version` is a `SemanticBuildVersion` rather than a string. This is somewhat counterintuitive and could break code that interacts with `project.version` in users' build scripts. An example of the kind of code that breaks can be seen in this gradle discussion forum topic:
https://discuss.gradle.org/t/is-it-possible-using-new-maven-publish-plugin-to-select-repository-to-publish-to-based-on-version-release-vs-snapshot/3696/2

Here we see a legitimate use case for users to call `String` methods on `project.version`

**Comment by vivin** [comment]
The type of `project.version` is actually `Object` as can be seen [here](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#getVersion%28%29), and Gradle  itself always uses `toString()` when working with the version.

Since the API defines the type as an `Object`, any code that works with the version necessarily has to call `toString()`, because it cannot assume that the version will always be a string (it usually ends up being so because we do things like `version = "1.0.0"`, which ends up making it a `String`).

While I agree that this behavior is inconvenient, I would argue that any code that calls `String` methods directly on `project.version` violates the Gradle API and should really be explicitly calling `project.version.toString()` first. Hence I would suggest that the problematic build-script be fixed; while slightly inconvenient, I don't think that it is too hard to do. TBF I'm kinda on the fence about this and the only thing that convinces me to err on the side of _not_ assuming that it is a `String` is because the type is `Object` as specified by the API.

**Comment by waynr** [comment]
@vivin thanks for the quick response! So when I look at the documentation you link in the "Extra Properties" section I see a usage of `version.EndsWith()`:

```
 ext.isSnapshot = version.endsWith("-SNAPSHOT")
 if (isSnapshot) {
     // do snapshot stuff
 }
```

Since the example doesn't explicitly set the `version` identifier it is presumably coming from one of the dynamic properties scopes listed shortly before the example:

> A project has 5 property 'scopes', which it searches for properties. You can access these properties by name in your build file, or by calling the project's
> property(String) method. The scopes are:
> -    The Project object itself. This scope includes any property getters and setters declared by the Project implementation class. For example, getRootProject() is accessible as the rootProject property. The properties of this scope are readable or writable depending on the presence of the corresponding getter or setter method.
> -    The extra properties of the project. Each project maintains a map of extra properties, which can contain any arbitrary name -> value pair. Once defined, the properties of this scope are readable and writable. See extra properties for more details.
> -   The extensions added to the project by the plugins. Each extension is available as a read-only property with the same name as the extension.
> -   The convention properties added to the project by the plugins. A plugin can add properties and methods to a project through the project's Convention object. The properties of this scope may be readable or writable, depending on the convention objects.
> -    The tasks of the project. A task is accessible by using its name as a property name. The properties of this scope are read-only. For example, a task called compile is accessible as the compile property.
> -    The extra properties and convention properties inherited from the project's parent, recursively up to the root project. The properties of this scope are read-only.

Given that this documentation is intended to explain the `Project` API, the safest assumption as a user is that the `version` property in the example comes from a `Project` object.

**Comment by waynr** [comment]
I think the most accurate thing we can say about the `Project` API is that the `getVersion()` method returns an `Object`. It seems like an open question as to the actual type of the `version` property of the `Project` class...if it's supposed to be `Object` then the documentation is currently wrong and should be fixed to use `version.toString().endsWith(...)`

**Comment by vivin** [comment]
@waynr I definitely agree; especially since the documentation says that Gradle internally uses `toString()` when it deals with versions. The problem with using `Object` is that it can mean pretty much anything. But presumably they left it that way so that you could include logic when figuring out the version. I think a better design might have been to put it behind an interface of some sort. There's a sort of implicit "interface" in that it is `Object` and that you must always call `toString()` when calling it, but that sort of thing really can't be enforced. So their example, while it works in most cases, is definitely misleading.
