### ISSUE TITLE
promotion of pre-release versions does not remove snapshotSuffix

### ISSUE THREAD

**Issue by rustycl0ck** [vivin/gradle-semantic-build-versioning#96]
When a pre-release version (like `1.2.2-alpha.4-SNAPSHOT` for example) is promoted to release, it is versioned as `1.2.2-SNAPSHOT` instead of the expected version `1.2.2-alpha.4`

**Comment by vivin** [comment]
Would you be able to show the exact command you've used and the output? Thanks!

**Comment by vivin** [comment]
This is working as expected (see [here](https://github.com/vivin/gradle-semantic-build-versioning#promotetorelease)). I know it's a little confusing that you have `promoteToRelease` and `release`. This is because we also account for the Java notion of release vs. snapshot builds. `promoteToRelease` only promotes a **semver** pre-release version to release. If you haven't supplied the `release` property, it will not get rid of the snapshot suffix. So to do what you want, you will need to include both: `-PpromoteToRelease -Prelease`.
